SocialMediaAggregator/SocialMediaAggregator/Controllers/FacebookController.cs
using Antlr.Runtime;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;
using SocialMediaAggregator.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SocialMediaAggregator.Controllers
{
    [Authorize]

    public class FacebookController : Controller
    {
        public static string email
        {
            get; set;
        }
        private ApplicationDbContext db = new ApplicationDbContext();

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult preferance()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult preferance(bool status)
        {
            try
            {
                Email f = db.email.Where(x => x.user == email).FirstOrDefault();
                f.status = status;
                db.SaveChanges();
                return RedirectToAction("Posts");
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Posts()
        {
            var id = User.Identity.GetUserId();

            var currentClaims = await UserManager.GetClaimsAsync(HttpContext.User.Identity.GetUserId());
            var accesstoken = currentClaims.FirstOrDefault(x => x.Type == "urn:tokens:facebook");
            if (accesstoken == null)
            {
                return (new HttpStatusCodeResult(HttpStatusCode.NotFound, "Token not found"));
            }
            string url = String.Format("https://graph.facebook.com/me?fields=id,picture.type(large),name,email,posts.fields(picture,message),likes,albums.fields(photos.fields(source)),feed.fields(picture,message)&redirect=false&redirect=false&access_token={0}", accesstoken.Value);
            HttpWebRequest request = WebRequest.Create(url) as HttpWebRequest;
            request.Method = "GET";
            using (HttpWebResponse response = await request.GetResponseAsync() as HttpWebResponse)
            {
                StreamReader reader = new StreamReader(response.GetResponseStream());
                string result = await reader.ReadToEndAsync();
                FacebookModel facebook = new JavaScriptSerializer().Deserialize<FacebookModel>(result);
                ViewBag.id = facebook.id;
                ViewBag.name = facebook.name;
                ViewBag.email = facebook.email;
                ViewBag.feed = facebook.feed.data;
                ViewBag.likes = facebook.likes.data;
                ViewBag.posts = facebook.posts.data;
                ViewBag.albums = facebook.albums.data;
                email = facebook.email;
                if (db.email.Where(x => x.user == facebook.email).Count() == 0)
                {
                    Email e = new Email();
                    e.user = facebook.email;
                    e.status = true;
                    db.email.Add(e);
                    db.SaveChanges();
                }
                Email f = db.email.Where(x => x.user == email).FirstOrDefault();
                ViewBag.status = f.status;

            }

            return View();
        }
    }
}

SocialMediaAggregator/SocialMediaAggregator/Views/Facebook/Posts.cshtml
@{
    ViewBag.Title = "Posts";
}
<script>
</script>


<div class="col">
    <div class="col-md-4">
        <h2>Profile</h2>
        <div class="card">
            <div class="container">
                <h4><b>Name: @Html.Raw(ViewBag.name)</b></h4>
                @if (ViewBag.status == true)
                {
                    <h4>
                    <b>Email:</b>
                    <br>
                    <b>@Html.Raw(ViewBag.email)</b>
                    </h4>
                }
            </div>
        </div>
        <ul class="nav flex-column">
            <li>@Html.ActionLink("Profile Settings", "preferance", "Facebook", new { @style = "color:blue" })</li>
        </ul>
    </div>
    <div class="col-md-4" style="padding: 10px">
        <div class="card" style="border: double; padding:10px; background-color: darkcyan">
            <h2 style="text-align:center">Posts</h2>
            @foreach (var item in ViewBag.posts)
            {
                <div class="card" style="border:double">
                    @if (item.picture != null)
                    {
                        <img src="@item.picture" alt="img" style="width:100%">
                    }
                    <div class="container">
                        <h4><b>@item.message</b></h4>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="col-md-4" style="padding: 10px">
        <div class="card" style="border: double; padding:10px; background-color: darkcyan">
            <h2 style="text-align:center">Feed</h2>
            @foreach (var item in ViewBag.feed)
            {
                <div class="card" style="border:double">
                    @if (item.picture != null)
                    {
                        <img src="@item.picture" alt="img" style="width:100%">
                    }
                    <div class="container">
                        <h4><b>@item.message</b></h4>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div class="col">
    
    <div class="col-md-6" style="border: double; padding:10px; background-color: darkcyan">
        <center>
            <h2 style="border:ridge">Likes</h2>
            <div class="card" style="border:ridge;padding:10px;">
                @foreach (var item in ViewBag.likes)
                {
                    <div class="card" style="border:ridge;padding:10px;">
                            <h4><b>@item.name</b></h4>
                    </div>
                }
            </div>
        </center>
    </div>
    <div class="col-md-6" style="border: double; padding:10px; background-color: darkcyan">
        <center>
            <h2 style="border: ridge">Photos</h2>
            <div class="card"style="border: ridge">
                @foreach (var item in ViewBag.albums)
                {
                    foreach (var i in item.photos)
                    {
                        foreach (var e in i.data)
                        {

                            <img src="@e.source" alt="img" style="width:20%">

                        }
                    }
                }
            </div>
        </center>
    </div>
      
</div>

SocialMediaAggregator/SocialMediaAggregator/Views/Facebook/preferance.cshtml
@model SocialMediaAggregator.Models.Email
@{
    ViewBag.Title = "Posts";
}
<script>
</script>
<h2>Profile</h2>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.user)
    @Html.AntiForgeryToken()

<div class="col">
    <div class="col-md-6">
        <div class="form-group">
            <h3>Status</h3>
            <h4>Tick the box to show email or untick to hide email</h4>
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-horizontal">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
        <div class="col-md-6">
             @Html.ActionLink("Back to Home Page","Posts", "Facebook",new { @class = "btn-primary-button" })
        </div>
    </div>
    }